# Generated by Django 3.0.7 on 2020-07-03 15:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='이름')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('gender', models.IntegerField(verbose_name='성별')),
                ('address', models.TextField(max_length=200, verbose_name='주소')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='최근로그인')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
