# Generated by Django 3.0.7 on 2020-07-03 17:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20200704_0200'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(default=0, max_length=200, verbose_name='주소'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=1, verbose_name='나이'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.IntegerField(default=1, verbose_name='성별'),
            preserve_default=False,
        ),
    ]
