# Generated by Django 3.0.7 on 2020-07-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20200708_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(max_length=200, null=True, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(null=True, verbose_name='나이'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.IntegerField(null=True, verbose_name='성별'),
        ),
    ]
