# Generated by Django 3.0.7 on 2020-07-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20200708_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='주소'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=1, verbose_name='나이'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.IntegerField(default=1, verbose_name='성별'),
            preserve_default=False,
        ),
    ]
