# Generated by Django 3.0.7 on 2020-07-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20200709_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.TextField(default=1, max_length=200, verbose_name='주소'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=1, verbose_name='나이'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.IntegerField(default=1, verbose_name='성별'),
            preserve_default=False,
        ),
    ]
