# Generated by Django 3.0.7 on 2020-06-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('email', models.EmailField(max_length=100, verbose_name='이메일')),
                ('password', models.CharField(max_length=100, verbose_name='비밀번호')),
                ('gender', models.IntegerField(verbose_name='성별')),
                ('address', models.TextField(max_length=200, verbose_name='주소')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='수정날짜')),
            ],
        ),
    ]
